### ISSUE TITLE
Cannot get  {userId, decodedToekn} from useKeycloka()

### ISSUE THREAD

**Issue by DEAN-Cherry** [JoseGoncalves/vue-keycloak#4]
![图片](https://github.com/JoseGoncalves/vue-keycloak/assets/76607677/a8d912d7-286b-4508-a886-36b310230ff7)

There is no definition about `userId` and `decodedToken` but written in the doc 

![图片](https://github.com/JoseGoncalves/vue-keycloak/assets/76607677/b4cec71f-4f95-4083-af72-ec1771cdcb76)

**Comment by JoseGoncalves** [comment]
Hi @DEAN-Cherry. It seems to me that you are using an old version of the library. This should not be an issue with the latest (v.2.4.0) version.

**Comment by DEAN-Cherry** [comment]
> Hi @DEAN-Cherry. It seems to me that you are using an old version of the library. This should not be an issue with the latest ([v2.4.0](https://github.com/JoseGoncalves/vue-keycloak/releases/tag/v2.4.0)) version.

Thanks, it works on v2.4.0, but got this `TS7016: Could not find a declaration file for module @josempgon/vue-keycloak.` Should I manually add a new declaration (.d.ts) file containing declare module '@josempgon/vue-keycloak' ?

**Comment by DEAN-Cherry** [comment]
> Hi @DEAN-Cherry. It seems to me that you are using an old version of the library. This should not be an issue with the latest ([v2.4.0](https://github.com/JoseGoncalves/vue-keycloak/releases/tag/v2.4.0)) version.

It works, thanks a lot.
